export interface RustWorkspaceFile {
  path: string;
  content: string;
}

export interface FuzzTemplateInput {
  contractName: string;
  files: RustWorkspaceFile[];
  targetName?: string;
}

export interface GeneratedFuzzFile {
  path: string;
  content: string;
}

export interface GeneratedFuzzTemplate {
  targetName: string;
  crateName: string;
  contractStructName: string | null;
  files: GeneratedFuzzFile[];
}

const readFile = (files: RustWorkspaceFile[], wantedPath: string) => {
  const normalizedWanted = wantedPath.replace(/\\/g, "/");
  const match = files.find(
    (file) => file.path.replace(/\\/g, "/") === normalizedWanted,
  );
  return match?.content ?? "";
};

const deriveCrateName = (contractName: string, files: RustWorkspaceFile[]) => {
  const cargoTomlPath = `${contractName}/Cargo.toml`;
  const cargoToml = readFile(files, cargoTomlPath);
  const match = cargoToml.match(/^\s*name\s*=\s*["']([^"']+)["']/m);
  const packageName = match?.[1] ?? contractName;
  return packageName.replace(/-/g, "_");
};

const deriveContractStructName = (
  contractName: string,
  files: RustWorkspaceFile[],
): string | null => {
  const libPath = `${contractName}/lib.rs`;
  const source = readFile(files, libPath);
  if (!source) {
    return null;
  }

  const contractStruct = source.match(
    /#\s*\[\s*contract\s*\][\s\S]*?pub\s+struct\s+([A-Za-z_][A-Za-z0-9_]*)/m,
  );

  return contractStruct?.[1] ?? null;
};

export function createSorobanFuzzTemplate(
  input: FuzzTemplateInput,
): GeneratedFuzzTemplate {
  const targetName =
    input.targetName?.trim().replace(/[^a-zA-Z0-9_]/g, "_") || "contract_fuzz";
  const crateName = deriveCrateName(input.contractName, input.files);
  const contractStructName = deriveContractStructName(
    input.contractName,
    input.files,
  );

  const fuzzCargoToml = `[package]
name = "${targetName}-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
soroban-sdk = { version = "22.0.0" }
contract_under_test = { package = "${crateName.replace(/_/g, "-")}", path = ".." }

[[bin]]
name = "${targetName}"
path = "fuzz_targets/${targetName}.rs"
test = false
doc = false
bench = false
`;

  const targetSource = `#![no_main]

use libfuzzer_sys::fuzz_target;
use soroban_sdk::{Bytes, Env};

use contract_under_test as _;

fuzz_target!(|data: &[u8]| {
    // Keep input bounded so local runs stay responsive.
    if data.len() > 4096 {
        return;
    }

    let env = Env::default();
    let bytes = Bytes::from_slice(&env, data);

    // TODO: Replace this scaffold with concrete invocations into your contract.
    // Example pattern:
    // 1. register contract in Env
    // 2. construct generated client
    // 3. call a method with fuzz-derived arguments
    // 4. assert invariants and let panics signal crashes
    let _ = bytes.len();
});
`;

  const readme = `# cargo-fuzz setup

This folder was generated by the IDE fuzzing workflow.

## Suggested next step

Edit fuzz_targets/${targetName}.rs and replace the TODO block with contract calls.
${
  contractStructName
    ? `Detected contract struct: ${contractStructName}`
    : "Contract struct could not be auto-detected; wire your generated client manually."
}
`;

  return {
    targetName,
    crateName,
    contractStructName,
    files: [
      {
        path: "fuzz/Cargo.toml",
        content: fuzzCargoToml,
      },
      {
        path: `fuzz/fuzz_targets/${targetName}.rs`,
        content: targetSource,
      },
      {
        path: "fuzz/README.md",
        content: readme,
      },
      {
        path: "fuzz/.gitignore",
        content: "artifacts\ncorpus\n",
      },
    ],
  };
}
